### ISSUE TITLE
speeding up downloading media

### ISSUE THREAD

**Issue by kingk110** [wiz0u/WTelegramBot#1]
Hello everybody
I am using the wTelegramBot.
at first I think there was error for some videos for security reasons but then it was solved.

Now I am asking if there is a way to speed up the download especially that my account that created the bot is premium account.
Sometimes I am getting only 5mbps download speed of 100 mbps bandwidth.

Is there a way to speed up the downloading media using the bot.
I am using 
`await using Stream fileStream = System.IO.File.Create(destinationFilePath);`
`var file = await bot.GetInfoAndDownloadFile(videoFileId, fileStream);`
for downloading.

all help is very appericiated
Regards

**Comment by wiz0u** [comment]
This should be fixed in version 7.7.1 via https://github.com/wiz0u/WTelegramClient/issues/261
