### ISSUE TITLE
WTelegram.Bot.GetUpdates() function do not run as expected

### ISSUE THREAD

**Issue by ghggn** [wiz0u/WTelegramBot#2]
when i use getupdates and set offset parem to -1 it still return all update instead of ignore old update

what i did 
1 turn off my bot 
2 send message to my bot
![image](https://github.com/wiz0u/WTelegramBot/assets/129544540/ab7a4368-cd3e-40d2-bfc2-a8f7a00034a6)
3 online my bot with set query update offset -1
![image](https://github.com/wiz0u/WTelegramBot/assets/129544540/bff43c5d-3c91-40d9-b257-8a8004992e29)
4 bot still recive all update instead of ignore old
![image](https://github.com/wiz0u/WTelegramBot/assets/129544540/8d1b868c-e2a2-48a7-9891-7c283f5f15cf)

and then i dedug my code and find that in source code Bot.cs the _state.PendingUpdates.Count is 1
but it should be 4 (cause i send 4 msg when bot offline )
![image](https://github.com/wiz0u/WTelegramBot/assets/129544540/128f6047-9cf1-473a-bf9c-4182426a7873)

i think it should be a bug.

**Comment by wiz0u** [comment]
This is more complex than it seems.

On the official cloud Bot API, their system is always running and transcribing Client API updates into Bot API updates. So telling it to GetUpdates(-1) works as expected.

But with WTelegramBot, we are not running all the time and on restart, the resync of past updates is happening in the background, progressively filling PendingUpdates (so you may get 1 when 'A' has been resync but not yet 'B', 'C', 'D')

I've decided to address this issue with a dropUpdates boolean on construction (see also issue #3)

**Comment by wiz0u** [comment]
I'm not satisfied with the solution. As we saw together, it still required a DropPendingUpdates() after a few seconds.

I'm working on something better.

**Comment by wiz0u** [comment]
fixed in v7.8.1

_(removed the constructor option, just call DropPendingUpdates quickly after constructor)_
