### ISSUE TITLE
Hope WelegramBot will truly ignore old update 

### ISSUE THREAD

**Issue by ghggn** [wiz0u/WTelegramBot#3]
when call http bot api `getUpdates` method and pass `offset ` with -1 it will ignore old update in server side.
but in WTelegramBot is will alway get all pending updates , since the `getUpdates` method is just copy the updates received by WTelegramClient .
when you call `dropPendingUpdates `, it's true that you will not get these old updates, but these old updates still be received with WTelegramCient , even if there has 10k pending updates .
the WTelegramBot just fetch them and ignore them in local side , not like http bot api (the old updates just ignored in server side so you won't receive the update you don't needed)

**Comment by wiz0u** [comment]
Actually, i think server-side, the official bot api does receive the Client API updates too.
It's just that they are not transmitted to you as Bot API.
So your question is just more on the network bandwidth usage & possible delay for converting/ignoring these updates.

**Comment by wiz0u** [comment]
The solution might be to just clear or delete table WTB_MBoxState from DB before starting the bot.
It will not try to resync all in-between updates.

**Comment by wiz0u** [comment]
I'm adding a dropUpdates bool on construction to disable resync of updates and truly ignore old updates for bots that don't want them
